name: My workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Manual approval
        id: manual-approval
        uses: mikeal/prompt-action@v2
        with:
          prompt: "Do you approve this deployment?"
        env:
          APPROVED: ${{ github.event.inputs.approved }}

      - name: Deploy code
        if: steps.manual-approval.outputs.response == 'true'
        run: make deploy
